### ISSUE TITLE
Duplicate border

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-java#57]
![image](https://cloud.githubusercontent.com/assets/542934/14109963/44e4d330-f5cd-11e5-9e16-53056f743a56.png)

**Comment by unv-unv** [comment]
Isn't it fixed already? In diff mode I didn't see duplicate frame border.

**Comment by VISTALL** [comment]
Yeah. In Consulo(IDEA) coexists two versions of Diff impl (new and old-deprecated)

Java plugin used old one, and i am waiting JB fix for it(minor issue, and sometime ago new api can't not replace all old api usage)

And forgot about this issue. Looks like they fixed it 

https://github.com/JetBrains/intellij-community/commit/66dedb13ba02d36cb318c14e943944cc0f68cdd3

Thanks, I think will fix it after sleep
