### ISSUE TITLE
Installing JDK

### ISSUE THREAD

**Issue by winalex** [consulo/consulo-java#67]
I've install http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
MacOsX. I tried to set in Consulo but can't select it say No SDK???

**Comment by VISTALL** [comment]
Hi. You need add JDK (Welcome Screen -> Configure -> Project Defaults -> Project Structure -> Bundles -> + (plus) -> JDK and select correct path).

I will fix auto-detection for JDK on Mac (forgot about this bug).

And will review New Project panel.

Thanks

**Comment by winalex** [comment]
I'm hitting /// like in unity but neather Java nor C# is doing auto commenting. Now also formatting shortcut didn't remove unused imports/usings

**Comment by VISTALL** [comment]
Tested in C# (unity, non unity projects). Inserting full doc on **///** works.

In Java there no **///**, you need type 
```java
   /**<and press enter>
```

As i known - Optimize imports is not enabled by default on **Reformat Code**.

Call reformat 

![](http://klikr.org/30ec90b08cbd42e9af07fdab9145.png)

And press **Show reformat dialog**, and check Optimize Imports once

**Comment by winalex** [comment]
Ok. You are right about comments. But when I put mouse over the function used somewhere and I've added comment before I didn't get any info of function like showing comment or something

**Comment by VISTALL** [comment]
![](http://klikr.org/442a21e80a350e8bab466467d406.png)

**Comment by winalex** [comment]
In C# no unity, when I enter the third /// comments show up
in Java /**<-- now I need to hit enter
In C# how this Documentation for start comes. Did you do some shortcut click. Doesn't showing anything on Mac???

**Comment by winalex** [comment]
<img width="1440" alt="screen shot 2017-03-25 at 3 47 04 pm" src="https://cloud.githubusercontent.com/assets/689092/24323180/5e65ee54-1172-11e7-9270-a643c4e65586.png">

**Comment by VISTALL** [comment]
In C# i just type 3rd slash, and it insert doc

![](http://klikr.org/848141248b5d7fcc05afed7f8196.gif)

I am only press slash. If doc not inserted - need example, and i will check it

**Comment by VISTALL** [comment]
This C# Doc insert like VS. Maybe need unify it

**Comment by winalex** [comment]
Also I saw in some IDE example what they used inside Unity C# dev team, the starting templates are much better like there is comments and/or regions separated areas public members, private members, constructors, public methods , static methods, so on

**Comment by VISTALL** [comment]
Automatize it - idk how. Consulo has arrangement for sorting members inside file. But - for now C# not support it. Sorry

![](http://klikr.org/59213dd30453338758f2c3ab3fed.png)
