### ISSUE TITLE
How to specify language level?

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-java#73]
I couldn't find a way to specify language level lower than JVM version.

For example, I have Java 1.8 but I want language features of 1.7. So I specified Settings / Compiler / Java / Project bytecode version = 1.7. But IDE still suggests to replace anonymous class with lambda expression (Java 1.8 feature).

I checked many places in Settings and Project Structure but didn't find another option to specify language level.

**Comment by VISTALL** [comment]
here
![](http://klikr.org/18ee691cc03c762bfbdefe94ae85.png)

**Comment by unv-unv** [comment]
Thanks.

**Comment by VISTALL** [comment]
Next time - use https://discuss.consulo.io , wanna split tasks & issues.

Thanks
