### ISSUE TITLE
Inspection 'equals() should check the class of its parameter' false positive if class is checked by method call

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-java#75]
If class equality is checked in method call, inspection shows unnecessary warning:
![java_inspection_equals_class_check_falsepositive](https://user-images.githubusercontent.com/16825982/27806637-641c9c3c-6044-11e7-8b25-43cf5795ccbc.png)

Example code:
```
public class Test
{
    public static boolean eqClass(Object obj1, Object obj2)
    {
        return (obj1 != null && obj2 != null && obj1.getClass() == obj2.getClass());
    }

    public class Foobar
    {
        int x = 0;

        public boolean equals(Object obj)
        {
            
            if (this == obj) return true;
            if (!eqClass(this, obj)) return false;
            return x == ((Foobar)obj).x;
        }
    }
}
```

**Comment by VISTALL** [comment]
IDEA bug.

I will leave it for future.

Thanks

**Comment by unv-unv** [comment]
OK, will turn off this inspection as a workaround.

**Comment by VISTALL** [comment]
In inspection setting - you can disable only **varargs** check

**Comment by VISTALL** [comment]
my bad - wrong inspection :)
