### ISSUE TITLE
Javadoc preview oversized

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-java#77]
This is very similar to other Windows scale issues with exception that text is twice as large in 200% scale as it should be (:
![java_javadoc_preview_oversized](https://user-images.githubusercontent.com/16825982/27933744-558382e4-62ab-11e7-9884-0bf130e7bacc.png)

**Comment by VISTALL** [comment]
oh. I will check it.

Thanks

**Comment by VISTALL** [comment]
fixed in platform
