### ISSUE TITLE
The plugin consulo.java failed to save settings and has been disabled

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-java#79]
Short after start event log shows: "Unable to save plugin settings: The plugin consulo.java failed to save settings and has been disabled. Please restart Consulo"

It doesn't affect work, but after IDE restart Java plugin is disabled and you must manually turn it on in Settings. Very annoying.

Consulo version: 2188
Java: 1.8.0
OS: Win10
Consulo is installed into C:\Program Files

**Comment by VISTALL** [comment]
Hello. Can you attach log?  (help -> show log in explorer)

Thanks

**Comment by unv-unv** [comment]
consulo.log: https://yadi.sk/i/uWlRjHX1u-gAWw

**Comment by VISTALL** [comment]
Hi. Looks like there index problems. Can you drop cache (File -> Invalidate caches -> Invalidate & Restart)

If after those actions, exceptions return - i need sample project for fix it. (problems in jsp files)

**Comment by unv-unv** [comment]
Seems that exceptions are gone. Thanks. If they return, I'll reopen this ticket, but now I'm closing it.

**Comment by VISTALL** [comment]
Thanks. I will wait:)
