### ISSUE TITLE
Before Lauch field in remote debug configuration infinitely widens up

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-java#89]
![изображение](https://user-images.githubusercontent.com/16825982/116322264-5bc50800-a7c4-11eb-858a-be62f5ade47a.png)

Label «There are no tasks to run before launch» slowly and unstoppably crawls to the right and the whole dialog quickly becomes unusable.

**Comment by VISTALL** [comment]
Hello. I will check and fix if need. Thanks
